# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|  
  config.vm.define "tvm1" do |tvm1|
    tvm1.vm.box = "generic/rhel8"
    tvm1.vm.hostname = "tvm1"
    tvm1.vm.box_url = "generic/rhel8"

    tvm1.vm.network :private_network, ip: "10.0.0.2"

    tvm1.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.customize ["modifyvm", :id, "--name", "tvm1"]
    end
    
    config.vm.provision "ansible" do |ansible|
      ansible.verbose = "v"
      ansible.playbook = "playbook.yml"
    end
  end    
end
