# -*- mode: ruby -*-
# vi: set ft=ruby :

IMAGE_NAME = "generic/rhel8"

Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
  end
  config.vbguest.auto_update = false

  config.vm.define "idm-server" do |master|
    master.vm.box = IMAGE_NAME
    master.vm.hostname = "idm-server.example.com"
    master.vm.network "private_network", ip: "10.0.0.2"
    master.vm.provision "ansible" do |ansible|
      ansible.groups = {
        "ipaservers" => ["idm-server"]
      }
      ansible.playbook = "provisioning/preparation-server.yml"
    end
  end

  config.vm.define "servera" do |node|
    node.vm.box = IMAGE_NAME
    node.vm.hostname = "servera.example.com"
    node.vm.network "private_network", ip: "10.0.0.3"
    node.vm.provision "ansible" do |ansible|
      ansible.groups = {
        "ipaservers" => ["idm-server"],
        "ipaclients" => ["servera"]
      }
      ansible.playbook = "provisioning/preparation-client.yml"
    end
  end

end