---
- name: Provision vm
  hosts: all
  become: true
  tasks:
    - name: Ensure packages are up-to-date
      yum:
       name: '*'
       state: latest
      register: result

    - name: debug result
      debug:
        var: result

    - name: Reboot after updates
      reboot:
      when: result.changed == true
