---
- name: prepare ipa server
  hosts: idm-server
  become: true

  tasks:
  - name: Set timezone to Europe/Amsterdam
    timezone:
      name: Europe/Amsterdam

  - name: Add epel-release repo
    yum:
      name: epel-release
      state: present

  - name: Add my common tools
    yum:
      name:
        - wget
        - vim
        - bind-utils
      state: present

  - name: Add chrony and firewall for ipa
    yum:
      name:
        - firewalld
        - chrony
      state: present

  - name: enable firewalld
    systemd:
      name: "{{ item }}"
      state: started
      enabled: yes
    with_items:
      - firewalld
      - chrony

  - name: delete the loopback address
    lineinfile:
      path: /etc/hosts
      regexp: '^127\.0\.0\.1.*idm.*'
      line: "# disable hostname's loopback"

  - name: add local name resolution
    blockinfile:
      path: /etc/hosts
      marker: "######"
      insertafter: "### Use local hosts file for name resolution"
      state: present
      block: |
        10.0.0.2 idm-server.example.com idm-server
        10.0.0.3 servera.example.com servera

  # need to update nss package or ipa server role will fail
  - name: yum update
    yum:
      name: '*'
      state: latest

  - name: include ipa server role
    include_role:
      name: ipaserver